apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: simple-controller
    app.kubernetes.io/name: metup
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-controller
  namespace: system
  labels:
    control-plane: simple-controller
    app.kubernetes.io/name: metup
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: simple-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: simple-controller
    spec:
      containers:
        - name: simple-controller
          image: localhost:5000/simple-controller:latest
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: simple-controller
      terminationGracePeriodSeconds: 10
