apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: simple-controller
    app.kubernetes.io/name: metup
    app.kubernetes.io/managed-by: kustomize
  name: simple-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-controller
  namespace: simple-controller
  labels:
    control-plane: simple-controller
    app.kubernetes.io/name: metup
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: simple-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: simple-controller
    spec:
      containers:
        - name: simple-controller
          image: localhost:5000/simple-controller:latest
          volumeMounts:
            - name: cert-volume
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
      serviceAccountName: simple-controller
      volumes:
        - name: cert-volume
          secret:
            secretName: simple-webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  name: simple-controller
  namespace: simple-controller
  labels:
    control-plane: simple-controller
    app.kubernetes.io/name: metup
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: simple-controller
  type: ClusterIP
