// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func HelloGopher() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Hi folks!</title><style>\n        body {\n            background-color: #007d9c; /* Golang style blue */\n            color: white;\n            font-family: Arial, sans-serif;\n            text-align: center;\n            padding: 50px;\n        }\n\n        img {\n            width: 400px;\n            height: auto;\n            animation: bounceIn 1s ease-in-out;\n        }\n\n        @keyframes bounceIn {\n            0% {\n                opacity: 0;\n                transform: scale(0.3) translateY(-100%);\n            }\n            50% {\n                opacity: 1;\n                transform: scale(1.05) translateY(0);\n            }\n            70% {\n                transform: scale(0.9) translateY(-15px);\n            }\n            100% {\n                transform: scale(1) translateY(0);\n            }\n        }\n    </style></head><body><h1>Hello GoMad</h1><img src=\"assets/gopher.png\" alt=\"Golang Gopher\"></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
