apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    gomad: "true"
  name: hello-gophers-gomad
  namespace: simple-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      gomad: "true"
  template:
    metadata:
      labels:
        app: hello
        gomad: "true"
    spec:
      containers:
        - image: localhost:5000/gopher-pprof:latest
          imagePullPolicy: Always
          name: gopher-pprof
          ports:
            - containerPort: 8080
              protocol: TCP
